services:

  api:
    image: pyscalp-datatracker
    restart: always
    container_name: api
    logging:
      driver: json-file
      options:
        max-size: "10m"
    command: python server.py
    env_file:
      - .env-app
    networks:
      - remote
    # ports:
    #   - "8135:8000"

  worker:
    image: pyscalp-datatracker
    restart: always
    container_name: worker
    logging:
      driver: json-file
      options:
        max-size: "20m"
    command: python worker.py
    env_file:
      - .env-app
    networks:
      - remote

networks:
  remote:
    external: true
    name: db_remote

