services:
  app:
    image: pyscalp-datatracker-api:latest
    container_name: api
    env_file:
      - .env
    networks:
      - remote
    ports:
      - "8000:8000"
    volumes:
      - logs:/app/api/logs  # Монтируем volume для логов
    environment:
      - LOG_FILE=/app/api/logs/requests.log

volumes:
  logs:

networks:
  remote:
    driver: bridge