"""pairs selected column

Revision ID: 1a2082fc222e
Revises: c2605af15062
Create Date: 2025-01-15 00:32:38.296556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2082fc222e'
down_revision: Union[str, None] = 'c2605af15062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairs', sa.Column('selected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pairs', 'selected')
    # ### end Alembic commands ###
