"""fix numeric overflow for prices 123456,1234

Revision ID: 1aab439d1aef
Revises: 55722e736077
Create Date: 2025-01-15 18:08:39.008428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aab439d1aef'
down_revision: Union[str, None] = '55722e736077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
