"""qty precision

Revision ID: 5d1c32db18b7
Revises: d18bb7754099
Create Date: 2025-03-09 21:56:15.041752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d1c32db18b7'
down_revision: Union[str, None] = 'd18bb7754099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairs', sa.Column('qty_precision', sa.Integer(), nullable=True))
    # op.alter_column('transactions', 'fee',
    #            existing_type=sa.NUMERIC(precision=18, scale=12),
    #            type_=sa.Numeric(precision=16, scale=10),
    #            existing_nullable=False)
    # op.alter_column('transactions', 'balance',
    #            existing_type=sa.NUMERIC(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('transactions', 'balance',
    #            existing_type=sa.NUMERIC(),
    #            nullable=True)
    # op.alter_column('transactions', 'fee',
    #            existing_type=sa.Numeric(precision=16, scale=10),
    #            type_=sa.NUMERIC(precision=18, scale=12),
    #            existing_nullable=False)
    op.drop_column('pairs', 'qty_precision')
    # ### end Alembic commands ###
