"""transaction value precision

Revision ID: a313eaec356f
Revises: 1aab439d1aef
Create Date: 2025-01-28 00:42:23.253787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a313eaec356f'
down_revision: Union[str, None] = '1aab439d1aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pairs', 'selected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pairs', 'selected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
