"""add order_id field to transactions

Revision ID: c2d88623ba6d
Revises: a313eaec356f
Create Date: 2025-02-11 04:33:30.487898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d88623ba6d'
down_revision: Union[str, None] = 'a313eaec356f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    import random
    import string

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('order_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'transactions', ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'order_id')
    # ### end Alembic commands ###
