"""transaction detail info

Revision ID: cf21e2a49eee
Revises: c2d88623ba6d
Create Date: 2025-02-11 17:34:10.994204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf21e2a49eee'
down_revision: Union[str, None] = 'c2d88623ba6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('quantity', sa.Numeric(precision=12, scale=6), nullable=False))
    op.add_column('transactions', sa.Column('fee', sa.Numeric(precision=18, scale=12), nullable=False))
    op.add_column('transactions', sa.Column('pair_id', sa.BigInteger(), nullable=False))
    op.alter_column('transactions', 'order_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'transactions', 'pairs', ['pair_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.alter_column('transactions', 'order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('transactions', 'pair_id')
    op.drop_column('transactions', 'fee')
    op.drop_column('transactions', 'quantity')
    # ### end Alembic commands ###
