"""balance in transactions

Revision ID: d18bb7754099
Revises: cf21e2a49eee
Create Date: 2025-02-11 19:22:27.261999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18bb7754099'
down_revision: Union[str, None] = 'cf21e2a49eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('balance', sa.Numeric(precision=10, scale=9), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'balance')
    # ### end Alembic commands ###
