services:

  nginx:
    image: nginx:1.27.4-alpine3.21
    container_name: nginx
    restart: always
    volumes:
     - ./config:/etc/nginx
    ports:
     - "80:80"
    networks:
      - remote

networks:
  remote:
    external: true
    name: db_remote