services:

  postgres:
    image: postgres:15.10
    container_name: postgres
    restart: always
    env_file:
      - .env-pg 
    networks:
      remote:
        ipv4_address: 172.22.1.3
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d pyscalp_datatracker" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:8.14.0
    restart: always
    env_file:
      - .env-pgadmin
    environment:
      PGADMIN_SERVER_PREFIX: /pgadmin
    ports:
      - "5050:80"
    networks:
      - remote
    depends_on:
      postgres:
        condition: service_healthy

  init:
    image: pyscalp-datatracker
    container_name: init-db
    command: alembic upgrade head
    env_file:
      - ../../.env-app
    networks:
      - remote
    depends_on:
      postgres:
        condition: service_healthy

networks:
  remote:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.1.0/28
