name: deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Run deploy via ssh
        run: |
          ssh -o StrictHostKeyChecking=no root@91.107.120.205 -p 56888 "\
            cd /root/PyScalpDatatracker && \
            make rebuild-api"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
